#!/bin/bash

# Besides the tar command, all other output to standard out must 
# be surpressed.  Otherwise, the tar stream will be corrupted.
pushd /tmp/src >/dev/null
if [ -d build ]; then
    # all build (deps) contents to tar stream
    tar cf - build
fi
popd >/dev/null